# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.11
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: hexdoc-dev
book_id: hexcasting:thehexbook
default_branch: main
github_repo: book-of-hexxy
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: HexxyBookModPlugin
hexdoc_plugin_classname: HexxyBookPlugin
java_lang:
    ext: java
    src: java
java_package: com/example/hexxybook
mod_display_name: Book of Hexxy
modid: hexxybook
multiloader: false
package_export_root: src/hexdoc_hexxybook/_export
package_name: hexdoc-hexxybook
package_slug: hexdoc_hexxybook
package_src: src/hexdoc_hexxybook
pages_url: https://book.hexxy.media
pattern_regex:
    per_world_value: 'true'
    regex: make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*(?:new )?(?:ActionRegistryEntry|OperationAction)\(\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)
pattern_registry: registry/HexxybookPatternRegistry.java
