modid = "hexxybook"
book = "hexcasting:thehexbook"
extra_books = [
    "hexgloop:hexgloopbook",
    "oneironaut:oneironautbook",
]
default_lang = "en_us"
default_branch = "main"

resource_dirs = [  # top takes priority
    "resources",
    { modid="oneironaut", internal=true },
    { modid="hexgloop", internal=true },
    { modid="hexcasting", internal=true },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hexxybook/_export/generated"

[textures]
enabled = false
missing = [
    "emi:tag/*",
    "hexgloop:fake_spellbook_for_rei",
    "minecraft:chest",
]

[template]
icon = "icon.png"
include = [
    "hexxybook",
    "oneironaut",
    "hexgloop",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Book of Hexxy"
author = "hexdoc-dev"
show_landing_text = true

[extra.hexcasting]
pattern_stubs = []
