modid = "hexxybook"
book = "hexcasting:thehexbook"
default_lang = "en_us"
default_branch = "main"

resource_dirs = [  # top takes priority
    "resources",
    { modid="hexcasting", internal=true },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hexxybook/_export/generated"

[template]
icon = "icon.png"
include = [
    "hexxybook",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Book of Hexxy"
author = "hexdoc-dev"
show_landing_text = true

[textures]
missing = [
    "emi:tag/*",
]

[extra.hexcasting]
pattern_stubs = []
